version: 2
 
sources:
  - name: raw_qwt
    database: "{{env_var('DBT_SOURCEDB', 'QWT_ANALYTICS_DEV')}}"
    schema: "{{env_var('DBT_RAWSCHEMA', 'RAW_DEV')}}"
    tables:
      - name: raw_Customers
      - name: raw_products
      - name: raw_orders
      - name: raw_orderdetails
      - name: raw_employees
      - name: raw_offices
      - name: raw_shipments
      - name: raw_suppliers